swagger: '2.0'

info:
  version: 1.0.0
  title: Furniture-IoT API Documentation
  contact:
    email: mylogicgate@gmail.com

host: eiwen17ce8.execute-api.eu-west-1.amazonaws.com
basePath: /prod
schemes:
 - https

paths:
  /user/login:
    post:
      summary: Logs user into the system
      operationId: user-login
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: username/password
        required: true
        schema:
          $ref: '#/definitions/UserLoginRequest'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserLoginResponse'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        422:
          description: Unprocessable Entity
        500:
          description: Internal Server Error
  /user/refresh:
    post:
      summary: Renew access_token and id_token using refresh_token
      operationId: user-refresh
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: tokens
        required: true
        schema:
          $ref: '#/definitions/UserRefreshRequest'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserRefreshResponse'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        422:
          description: Unprocessable Entity
        500:
          description: Internal Server Error
  /user/signup:
    post:
      summary: Signup a new user account
      operationId: user-signup
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: username/password
        required: true
        schema:
          $ref: '#/definitions/UserSignupRequest'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserResponse'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        422:
          description: Unprocessable Entity
        500:
          description: Internal Server Error
  /user/{username}/verify:
    get:
      summary: Verify user's email
      operationId: user-verify
      produces:
      - application/json
      parameters:
      - name: username
        in: path
        type: string
        description: username of the user
        required: true
      - name: code
        in: query
        type: string
        description: Confirmation code
        required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserVerifyResponse'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        422:
          description: Unprocessable Entity
        500:
          description: Internal Server Error
  /user/{username}/forgot-password:
    post:
      summary: Forgot user password
      operationId: user-forgot-password
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: username
        in: path
        type: string
        description: username of the user
        required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserForgotResponse'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        422:
          description: Unprocessable Entity
        500:
          description: Internal Server Error
  /user/{username}/reset-password:
    post:
      summary: Reset user password
      operationId: user-reset-password
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: username
        in: path
        type: string
        description: username of the user
        required: true
      - in: body
        name: body
        description: reset password data
        required: true
        schema:
          $ref: '#/definitions/UserResetRequest'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserResetResponse'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        422:
          description: Unprocessable Entity
        500:
          description: Internal Server Error
  /user/me:
    get:
      summary: Get own user profile
      operationId: user-me-get
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserResponse'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        422:
          description: Unprocessable Entity
        500:
          description: Internal Server Error
      security:
      - id_token: []
    put:
      summary: Update own user
      operationId: user-me-update
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: User data that needs to be updated
        required: true
        schema:
          $ref: '#/definitions/UserUpdateRequest'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserResponse'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        422:
          description: Unprocessable Entity
        500:
          description: Internal Server Error
      security:
      - id_token: []
    delete:
      summary: Delete own user
      operationId: user-me-delete
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/DeletedUserResponse'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        422:
          description: Unprocessable Entity
        500:
          description: Internal Server Error
      security:
      - id_token: []
  /device:
    post:
      summary: Create device
      operationId: device-create
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: device_id
        required: true
        schema:
          $ref: '#/definitions/DeviceCreateRequest'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/DeviceResponse'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        422:
          description: Unprocessable Entity
        500:
          description: Internal Server Error
      security:
      - id_token: []
  /data/device/{deviceId}:
    get:
      summary: Get device data by deviceId & from/to time range
      operationId: data-get-device
      produces:
      - application/json
      parameters:
      - name: deviceId
        in: path
        type: string
        description: Id of the device
        required: true
      - name: from
        in: query
        type: integer
        description: Start time (Unix timestamp in second)
        required: true
      - name: to
        in: query
        type: integer
        description: End time (Unix timestamp in second)
        required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/GetDeviceDataResponse'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        422:
          description: Unprocessable Entity
        500:
          description: Internal Server Error
      security:
      - id_token: []
  /data/device/{deviceId}/latest:
    get:
      summary: Get latest device data by deviceId
      operationId: data-get-device-latest
      produces:
      - application/json
      parameters:
      - name: deviceId
        in: path
        type: string
        description: Id of the device
        required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/GetDeviceLatestDataResponse'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        422:
          description: Unprocessable Entity
        500:
          description: Internal Server Error
      security:
      - id_token: []
  /data/me:
    get:
      summary: Get user's own device data by from/to time range
      operationId: data-get-me
      produces:
      - application/json
      parameters:
      - name: from
        in: query
        type: integer
        description: Start time (Unix timestamp in second)
        required: true
      - name: to
        in: query
        type: integer
        description: End time (Unix timestamp in second)
        required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/GetDeviceDataResponse'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        422:
          description: Unprocessable Entity
        500:
          description: Internal Server Error
      security:
      - id_token: []
  /data/me/latest:
    get:
      summary: Get user's own latest device data
      operationId: data-get-me-latest
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/GetDeviceLatestDataResponse'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        422:
          description: Unprocessable Entity
        500:
          description: Internal Server Error
      security:
      - id_token: []

securityDefinitions:
  id_token:
    type: apiKey
    name: Authorization
    in: header

definitions:
  UserLoginRequest:
    type: object
    required:
    - password
    properties:
      username:
        type: string
      password:
        type: string
  UserRefreshRequest:
    type: object
    required:
    - refresh_token
    properties:
      refresh_token:
        type: string
  UserSignupRequest:
    type: object
    required:
    - username
    - email
    - password
    properties:
      username:
        type: string
      email:
        type: string
      password:
        type: string
      first_name:
        type: string
      last_name:
        type: string
  UserResetRequest:
    type: object
    required:
    - code
    - password
    properties:
      code:
        type: string
      password:
        type: string
  UserUpdateRequest:
    type: object
    properties:
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      new_password:
        type: string
      access_token:
        type: string

  DeviceCreateRequest:
    type: object
    required:
    - device_id
    properties:
      device_id:
        type: string

  UserLoginResponse:
    type: object
    properties:
      refresh_token:
        type: string
      access_token:
        type: string
      id_token:
        type: string
  UserRefreshResponse:
    type: object
    properties:
      access_token:
        type: string
      id_token:
        type: string
  UserResponse:
    type: object
    properties:
      username:
        type: string
      email:
        type: string
      verified:
        type: boolean
      created_at:
        type: string
        format: date-time
      timestamp:
        type: number
  UserVerifyResponse:
    type: object
    properties:
      verified:
        type: boolean
  UserForgotResponse:
    type: object
    properties:
      forgot:
        type: boolean
  UserResetResponse:
    type: object
    properties:
      reset:
        type: boolean
  DeletedUserResponse:
    type: object
    properties:
      Id:
        type: string

  DeviceResponse:
    type: object
    properties:
      device_id:
        type: string
      username:
        type: string
      created_at:
        type: string
      timestamp:
        type: string

  DeviceData:
    type: object
    properties:
      deviceId:
        type: string
      timestamp:
        type: integer
  GetDeviceDataResponse:
    type: object
    properties:
      deviceId:
        type: string
      deviceData:
        type: array
        items:
          $ref: '#/definitions/DeviceData'
  GetDeviceLatestDataResponse:
    type: object
    properties:
      deviceId:
        type: string
      deviceData:
        $ref: '#/definitions/DeviceData'
